export const ALL_DOMAINS = {
  B2B: "b2b",
  SERVICES: "services",
  AGRI_SERVICES: "agri-services",
  HEALTHCARE_SERVICES: "healthcare-service"
}


export const SERVICES_DOMAINS = {
  B2B: "b2b",
  SERVICES: "services",
  AGRI_SERVICES: "ONDC:SRV14",
  HEALTHCARE_SERVICES: "ONDC:SRV13"
}


export const AGRI_HEALTHCARE_STATUS =
  [
    "IN_TRANSIT",
    "AT_LOCATION",
    "COLLECTED_BY_AGENT",
    "RECEIVED_AT_LAB",
    "TEST_COMPLETED",
    "REPORT_GENERATED",
    "REPORT_SHARED"
  ];

export const AGRI_HEALTHCARE_STATUS_OBJECT =
{
  IN_TRANSIT: "IN_TRANSIT",
  AT_LOCATION: "AT_LOCATION",
  COLLECTED_BY_AGENT: "COLLECTED_BY_AGENT",
  RECEIVED_AT_LAB: "RECEIVED_AT_LAB",
  TEST_COMPLETED: "TEST_COMPLETED",
  REPORT_GENERATED: "REPORT_GENERATED",
  REPORT_SHARED: "REPORT_SHARED"
}

